Repository Capstone-499-AGMEETING1/AGMEETING, pull requests merged in 2021-11, with the labels that each got.

#166 Merge Upstream
  client/Component/wrapper.js
  package-lock.json
  public/.DS_Store
  server/server.js
Labels: Task

#165 Update Sidebar to Match Wireframe
  client/components/dashboard/DashboardSidebar.js
Labels: Task

#168 Create week-9.md
  documentation/reports/week-9.md
Labels: Chore

#169 Update Land.js
  client/Land.js
Labels: Task

#167 NavBar v0.1
  client/components/dashboard/NavBar.js
Labels: Task

#170 Update week-9.md
  documentation/reports/week-9.md
Labels: Chore

#171 Update week-9.md
  documentation/reports/week-9.md
Labels: Chore

#172 Create 110521 Minutes.pdf
  documentation/minutes/110521 Minutes.pdf
Labels: Chore

#173 Tinkering with app.js
  client/App.js
  config/theme/index.js
Labels: bug, question, Task

#174 Update week-9.md
  documentation/reports/week-9.md
Labels: Chore

#187 Create week-11.md
  documentation/reports/week-11.md
Labels: Chore

#184 Add Registered/Logged In User Lists
  client/components/agenda/Agenda.js
  client/components/dashboard/DashboardSidebar.js
  client/components/users-list/LoggedInUsers.js
  client/components/users-list/RegisteredUsers.js
  client/components/users-list/UserList.js
  client/contexts/SettingsContext.js
  client/routes.js
Labels: Task

#189 Update week-11.md
  documentation/reports/week-11.md
Labels: Chore

#186 Create Google Form
  documentation/peer-testing/peer-testing.md
Labels: Chore

#188 Settings page
  client/SettingsDrawer.js
  client/components/dashboard/DashboardSidebar.js
  client/components/settings/MainSettingsPage.js
  client/components/vault/Vault.js
  client/routes.js
Labels: Task

#192 Update week-11.md
  documentation/reports/week-11.md
Labels: Chore

#191 Create 111921 Minutes.pdf
  documentation/minutes/111921 Minutes.pdf
Labels: Chore

#194 Update week-11.md
  documentation/reports/week-11.md
Labels: Chore

#190 Content Message Prototype
  client/components/ContentMessage/Message.js
  client/components/dashboard/DashboardSidebar.js
  client/routes.js
Labels: Task

#193 Roll Call Prototype
  client/Land.js
  client/components/dashboard/DashboardSidebar.js
  client/components/roll-call/RollCall.js
  client/routes.js
Labels: Task

#202 Merge with main
  documentation/peer-testing/peer-testing.md
Labels: Chore

#205 Login and Register - Initial Component Creation
  client/App.js
  client/Land.js
  client/components/authentication/login/Login.js
  client/components/authentication/login/LoginAmplify.js
  client/components/authentication/login/LoginAuth0.js
  client/components/authentication/login/LoginFirebase.js
  client/components/authentication/login/LoginJWT.js
  client/components/authentication/register/Register.js
  client/components/authentication/register/RegisterAmplify.js
  client/components/authentication/register/RegisterAuth0.js
  client/components/authentication/register/RegisterFirebase.js
  client/components/authentication/register/RegisterJWT.js
  client/components/dashboard/NavBar.js
  client/contexts/JWTContext.js
  client/hooks/useAuth.js
  client/hooks/useMounted.js
  client/lib/gtm.js
  client/routes.js
  package-lock.json
  package.json
Labels: Task

#210 Add Tasks for Peer Testing
  documentation/peer-testing/peer-testing.md
Labels: Chore

#211 Fixes to Land.js
  client/App.js
  client/Land.js
  client/components/settings/MainSettingsPage.js
Labels: Task

#212 Update peer-testing.md
  documentation/peer-testing/peer-testing.md
Labels: Chore

#213 Update peer-testing.md
  documentation/peer-testing/peer-testing.md
Labels: Chore

#220 Update peer-testing.md
  documentation/peer-testing/peer-testing.md
Labels: Chore

#221 fixed font issue on land.js
  client/Land.js
Labels: bug

#227 Create week-12.md
  documentation/reports/week-12.md
Labels: Chore

#230 Update peer-testing.md
  documentation/peer-testing/peer-testing.md
Labels: Chore

#231 Create 112621 Minutes.pdf
  documentation/minutes/112621 Minutes.pdf
Labels: Chore

#228 Updated roll call
  client/components/dashboard/DashboardSidebar.js
  client/components/roll-call/RollCall.js
  client/routes.js
Labels: Task

#233 Add Session Notes
  documentation/peer-testing/peer-testing.md
Labels: Chore

#229 Update week-12.md
  documentation/reports/week-12.md
Labels: Chore

#234 Update peer-testing.md
  documentation/peer-testing/peer-testing.md
Labels: Chore

#235 Update peer-testing.md
  documentation/peer-testing/peer-testing.md
Labels: Chore

#236 Update week-12.md
  documentation/reports/week-12.md
Labels: Chore

#237 Video upload
  documentation/peer-testing/video-upload.md
Labels: Chore

#232 Update week-12.md
  documentation/reports/week-12.md
Labels: Chore

#243 Create description.md
  documentation/peer-testing/description.md
Labels: Chore
