Repository Capstone-499-AGMEETING1/AGMEETING, pull requests merged in 2021-10, with the labels that each got.

#13 Carson Report
  documentation/reports/week-5.md
Labels: Exploration

#14 Update week-5.md
  documentation/reports/week-5.md
Labels: Exploration

#24 Update Documentation closes #12
  documentation/reports/week-5.md
Labels: Exploration

#23 Tech Stack Report
  .DS_Store
  documentation/requirements-report/tech-stack.pdf
Labels: Chore

#26 Adding project description documentation Closes #17
  documentation/requirements-report/Project Description.pdf
Labels: Chore

#25 Testing Report
  documentation/requirements-report/testing-strategy.pdf
Labels: Chore

#30 Update week-5.md
  documentation/reports/week-5.md
Labels: Exploration

#73 Create Group Evaluation Template
  documentation/requirements-report/group-evaluation.md
Labels: Chore

#83 Update week-6.md Closes #77
  documentation/reports/week-6.md
Labels: Chore

#79 Adding video Closes #22 Closes #36
  documentation/requirements-report/Video Presentation
Labels: Chore

#85 Cyclops Evaluations
  documentation/requirements-report/group-evaluation.md
Labels: Chore

#87 Update week-6.md
  documentation/reports/week-6.md
Labels: Chore

#89 Create 100821 Minutes.pdf
  documentation/minutes/100821 Minutes.pdf
Labels: Chore

#102 Update group-evaluation.md
  documentation/requirements-report/group-evaluation.md
Labels: Chore

#103 Update group-evaluation.md
  documentation/requirements-report/group-evaluation.md
Labels: Chore

#104 Update group-evaluation.md Closes #41 Closes #53
  documentation/requirements-report/group-evaluation.md
Labels: Chore

#115 Project Description/User Groups Feedback Changes. Closes #97
  documentation/requirements-report/Project Description.pdf
Labels: Chore

#119 Install Material UI
  client/constants.js
  package-lock.json
  package.json
  webpack.base.js
  webpack.client.js
Labels: Task

#124 Update user-stories.md Closes #109
  documentation/requirements-report/user-stories.md
Labels: Task

#125 Update week-7.md Closes #93
  documentation/reports/week-7.md
Labels: Chore

#126 Update user-stories.md
  documentation/requirements-report/user-stories.md
Labels: Task

#129 Update week-7.md
  documentation/reports/week-7.md
Labels: Chore

#150 Repo Merge
  .gitignore
  client/App.js
  client/Land.js
  client/RTL.js
  client/components/dashboard/Layout.js
  client/components/in-session/InSession.js
  client/contexts/SettingsContext.js
  client/main.js
  client/routes.js
  config/theme/index.js
  package-lock.json
  package.json
  server/server.js
  webpack.base.js
  webpack.client.js
Labels: Task

#151 quick fix
  package-lock.json
  package.json
Labels: Chore

#157 Ryan week8
  client/components/vault/Vault.js
  client/routes.js
Labels: Task

#158 Update week-8.md
  documentation/reports/week-8.md
Labels: Chore

#160 Update week-8.md
  documentation/reports/week-8.md
Labels: Chore

#159 interactions page v0.1
  client/components/interactions/Interactions.js
  client/routes.js
Labels: Task

#162 Update week-8.md
  documentation/reports/week-8.md
Labels: Chore

#161 agenda page v0.1
  client/components/agenda/Agenda.js
  client/routes.js
Labels: Task
